/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateLikeRequest {
  /** Like target ID */
  targetId: number;
  /** Like target type */
  targetType: string;
}
