/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBadgeCollectionsResponseBadgesItem } from './GetBadgeCollectionsResponseBadgesItem';

export interface GetBadgeCollectionsResponse {
  /** 뱃지 도감 목록 */
  badges: GetBadgeCollectionsResponseBadgesItem[];
}
