/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 뱃지 태그
 */
export type GetBadgeCollectionsResponseBadgesItemTag = {
  /**
   * 뱃지 이미지 URL
   * @nullable
   */
  imageUrl?: string | null;
  /** 태그 이름 */
  name: string;
  /** 태그 설명 */
  description: string;
  /** 태그 ID */
  id: number;
};
