/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBookmarkedReflectionsResponsePosts } from './GetBookmarkedReflectionsResponsePosts';

export interface GetBookmarkedReflectionsResponse {
  posts?: GetBookmarkedReflectionsResponsePosts;
}
