/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBadgeCollectionsResponseBadgesItemTag } from './GetBadgeCollectionsResponseBadgesItemTag';

export type GetBadgeCollectionsResponseBadgesItem = {
  /** 뱃지 최초 획득 시각 */
  createdAt: string;
  /** 뱃지 레벨 */
  level: number;
  /** 해당 태그로 작성한 글 수 */
  postCount: number;
  /** 뱃지 태그 */
  tag: GetBadgeCollectionsResponseBadgesItemTag;
  /** 도감 항목 ID */
  id: number;
};
