/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetContestOccurrencesResponseOccurrencesContentItem } from './GetContestOccurrencesResponseOccurrencesContentItem';
import type { GetContestOccurrencesResponseOccurrencesPageInfo } from './GetContestOccurrencesResponseOccurrencesPageInfo';

export type GetContestOccurrencesResponseOccurrences = {
  /** Page Info */
  pageInfo: GetContestOccurrencesResponseOccurrencesPageInfo;
  /** Content */
  content: GetContestOccurrencesResponseOccurrencesContentItem[];
};
