/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetContestOccurrencesResponseOccurrencesContentItemContest = {
  /** Contest Name */
  name: string;
  /** Contest ID */
  id: number;
};
