/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Job Description Information
 */
export type GetJobApplicationResponseJobDescription = {
  /** Job Description */
  description: string;
  /** Job Location */
  location: string;
  /** Job Title */
  title: string;
};
