/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Company
 */
export type GetJobPostingsResponsePostingsContentItemCompany = {
  /** Company Name */
  name: string;
  /** Company ID */
  id: string;
};
