/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetJobApplicationsResponseApplicationsContentItemCompany } from './GetJobApplicationsResponseApplicationsContentItemCompany';

export type GetJobApplicationsResponseApplicationsContentItem = {
  company?: GetJobApplicationsResponseApplicationsContentItemCompany;
  /** Application ID */
  id: number;
};
