/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetJobPostingsResponsePostingsContentItem } from './GetJobPostingsResponsePostingsContentItem';
import type { GetJobPostingsResponsePostingsPageInfo } from './GetJobPostingsResponsePostingsPageInfo';

export type GetJobPostingsResponsePostings = {
  /** Page Info */
  pageInfo: GetJobPostingsResponsePostingsPageInfo;
  /** Content */
  content: GetJobPostingsResponsePostingsContentItem[];
};
