/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProvidersResponseProviders } from './GetProvidersResponseProviders';

export interface GetProvidersResponse {
  providers?: GetProvidersResponseProviders;
}
