/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetReflectionActivitiesResponseActivitiesItem = {
  /** Activity Date */
  date: string;
  /** Number of Reflections */
  count: number;
};
