/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetReflectionActivitiesResponseActivitiesItem } from './GetReflectionActivitiesResponseActivitiesItem';

export interface GetReflectionActivitiesResponse {
  /** List of Activities */
  activities: GetReflectionActivitiesResponseActivitiesItem[];
}
