/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetReflectionsResponseReflectionsNodesItemContentProject = {
  /**
   * Project Name
   * @nullable
   */
  name?: string | null;
  /**
   * Project ID
   * @nullable
   */
  id?: number | null;
};
