/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { SearchResponseResultsContentItem } from './SearchResponseResultsContentItem';
import type { SearchResponseResultsPageInfo } from './SearchResponseResultsPageInfo';

export type SearchResponseResults = {
  /** Page Info */
  pageInfo: SearchResponseResultsPageInfo;
  /** Content */
  content: SearchResponseResultsContentItem[];
};
