/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchResponseResultsContentItem = {
  /** Result Name */
  name: string;
  /** Result ID */
  id: number;
};
