/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateReflectionRequest {
  /**
   * Experience ID
   * @nullable
   */
  experienceId?: number | null;
  /** Content */
  content: string;
}
