/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { GetBadgeCollectionsResponse } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getBadgeCollectionsResponse200 = {
  data: GetBadgeCollectionsResponse;
  status: 200;
};

export type getBadgeCollectionsResponseSuccess =
  getBadgeCollectionsResponse200 & {
    headers: Headers;
  };
export type getBadgeCollectionsResponse = getBadgeCollectionsResponseSuccess;

export const getGetBadgeCollectionsUrl = (userId: string) => {
  return `/users/${userId}/badges`;
};

/**
 * 유저의 뱃지 도감을 조회합니다.
 * @summary Get Badge Collections
 */
export const getBadgeCollections = async (
  userId: string,
  options?: RequestInit,
): Promise<getBadgeCollectionsResponse> => {
  return api<getBadgeCollectionsResponse>(getGetBadgeCollectionsUrl(userId), {
    ...options,
    method: 'GET',
  });
};

export const getGetBadgeCollectionsQueryKey = (userId: string) => {
  return [`/users/${userId}/badges`] as const;
};

export const getGetBadgeCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBadgeCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBadgeCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBadgeCollectionsQueryKey(userId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBadgeCollections>>
  > = ({ signal }) =>
    getBadgeCollections(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBadgeCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBadgeCollectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBadgeCollections>>
>;
export type GetBadgeCollectionsQueryError = ErrorType<unknown>;

export function useGetBadgeCollections<
  TData = Awaited<ReturnType<typeof getBadgeCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBadgeCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBadgeCollections>>,
          TError,
          Awaited<ReturnType<typeof getBadgeCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBadgeCollections<
  TData = Awaited<ReturnType<typeof getBadgeCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBadgeCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBadgeCollections>>,
          TError,
          Awaited<ReturnType<typeof getBadgeCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBadgeCollections<
  TData = Awaited<ReturnType<typeof getBadgeCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBadgeCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Badge Collections
 */

export function useGetBadgeCollections<
  TData = Awaited<ReturnType<typeof getBadgeCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBadgeCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBadgeCollectionsQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
