/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { CreateLikeRequest, CreateLikeResponse } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type createLikeResponse201 = {
  data: CreateLikeResponse;
  status: 201;
};

export type createLikeResponseSuccess = createLikeResponse201 & {
  headers: Headers;
};
export type createLikeResponse = createLikeResponseSuccess;

export const getCreateLikeUrl = () => {
  return `/likes`;
};

/**
 * Create Like
 * @summary Create Like
 */
export const createLike = async (
  createLikeRequest?: CreateLikeRequest,
  options?: RequestInit,
): Promise<createLikeResponse> => {
  return api<createLikeResponse>(getCreateLikeUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLikeRequest),
  });
};

export const getCreateLikeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLike>>,
    TError,
    { data?: CreateLikeRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLike>>,
  TError,
  { data?: CreateLikeRequest },
  TContext
> => {
  const mutationKey = ['createLike'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLike>>,
    { data?: CreateLikeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createLike(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLike>>
>;
export type CreateLikeMutationBody = CreateLikeRequest | undefined;
export type CreateLikeMutationError = ErrorType<unknown>;

/**
 * @summary Create Like
 */
export const useCreateLike = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLike>>,
      TError,
      { data?: CreateLikeRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLike>>,
  TError,
  { data?: CreateLikeRequest },
  TContext
> => {
  return useMutation(getCreateLikeMutationOptions(options), queryClient);
};
export type deleteLikeResponse200 = {
  data: CreateLikeResponse;
  status: 200;
};

export type deleteLikeResponseSuccess = deleteLikeResponse200 & {
  headers: Headers;
};
export type deleteLikeResponse = deleteLikeResponseSuccess;

export const getDeleteLikeUrl = () => {
  return `/likes`;
};

/**
 * Delete Like
 * @summary Delete Like
 */
export const deleteLike = async (
  createLikeRequest?: CreateLikeRequest,
  options?: RequestInit,
): Promise<deleteLikeResponse> => {
  return api<deleteLikeResponse>(getDeleteLikeUrl(), {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLikeRequest),
  });
};

export const getDeleteLikeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLike>>,
    TError,
    { data?: CreateLikeRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLike>>,
  TError,
  { data?: CreateLikeRequest },
  TContext
> => {
  const mutationKey = ['deleteLike'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLike>>,
    { data?: CreateLikeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteLike(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLike>>
>;
export type DeleteLikeMutationBody = CreateLikeRequest | undefined;
export type DeleteLikeMutationError = ErrorType<unknown>;

/**
 * @summary Delete Like
 */
export const useDeleteLike = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLike>>,
      TError,
      { data?: CreateLikeRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLike>>,
  TError,
  { data?: CreateLikeRequest },
  TContext
> => {
  return useMutation(getDeleteLikeMutationOptions(options), queryClient);
};
