/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreateJobApplicationRequest,
  CreateJobApplicationResponse,
  GetJobApplicationFilesResponse,
  GetJobApplicationResponse,
  GetJobApplicationsResponse,
  GetMyJobApplicationsParams,
  UploadJobApplicationFileRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createJobApplicationResponse201 = {
  data: CreateJobApplicationResponse;
  status: 201;
};

export type createJobApplicationResponseSuccess =
  createJobApplicationResponse201 & {
    headers: Headers;
  };
export type createJobApplicationResponse = createJobApplicationResponseSuccess;

export const getCreateJobApplicationUrl = () => {
  return `/applications`;
};

/**
 * Create Job Application
 * @summary Create Job Application
 */
export const createJobApplication = async (
  createJobApplicationRequest?: CreateJobApplicationRequest,
  options?: RequestInit,
): Promise<createJobApplicationResponse> => {
  return api<createJobApplicationResponse>(getCreateJobApplicationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createJobApplicationRequest),
  });
};

export const getCreateJobApplicationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createJobApplication>>,
    TError,
    { data?: CreateJobApplicationRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createJobApplication>>,
  TError,
  { data?: CreateJobApplicationRequest },
  TContext
> => {
  const mutationKey = ['createJobApplication'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createJobApplication>>,
    { data?: CreateJobApplicationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createJobApplication(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateJobApplicationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createJobApplication>>
>;
export type CreateJobApplicationMutationBody =
  | CreateJobApplicationRequest
  | undefined;
export type CreateJobApplicationMutationError = ErrorType<unknown>;

/**
 * @summary Create Job Application
 */
export const useCreateJobApplication = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createJobApplication>>,
      TError,
      { data?: CreateJobApplicationRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createJobApplication>>,
  TError,
  { data?: CreateJobApplicationRequest },
  TContext
> => {
  return useMutation(
    getCreateJobApplicationMutationOptions(options),
    queryClient,
  );
};
export type getMyJobApplicationsResponse200 = {
  data: GetJobApplicationsResponse;
  status: 200;
};

export type getMyJobApplicationsResponseSuccess =
  getMyJobApplicationsResponse200 & {
    headers: Headers;
  };
export type getMyJobApplicationsResponse = getMyJobApplicationsResponseSuccess;

export const getGetMyJobApplicationsUrl = (
  params: GetMyJobApplicationsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/applications/me?${stringifiedParams}`
    : `/applications/me`;
};

/**
 * Get My Job Applications
 * @summary Get My Job Applications
 */
export const getMyJobApplications = async (
  params: GetMyJobApplicationsParams,
  options?: RequestInit,
): Promise<getMyJobApplicationsResponse> => {
  return api<getMyJobApplicationsResponse>(getGetMyJobApplicationsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetMyJobApplicationsQueryKey = (
  params?: GetMyJobApplicationsParams,
) => {
  return [`/applications/me`, ...(params ? [params] : [])] as const;
};

export const getGetMyJobApplicationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMyJobApplicationsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyJobApplications>>
  > = ({ signal }) =>
    getMyJobApplications(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyJobApplications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyJobApplicationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyJobApplications>>
>;
export type GetMyJobApplicationsQueryError = ErrorType<unknown>;

export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyJobApplications>>,
          TError,
          Awaited<ReturnType<typeof getMyJobApplications>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyJobApplications>>,
          TError,
          Awaited<ReturnType<typeof getMyJobApplications>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get My Job Applications
 */

export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyJobApplicationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getJobApplicationResponse200 = {
  data: GetJobApplicationResponse;
  status: 200;
};

export type getJobApplicationResponseSuccess = getJobApplicationResponse200 & {
  headers: Headers;
};
export type getJobApplicationResponse = getJobApplicationResponseSuccess;

export const getGetJobApplicationUrl = (applicationId: string) => {
  return `/applications/${applicationId}`;
};

/**
 * Get Job Application by ID
 * @summary Get Job Application
 */
export const getJobApplication = async (
  applicationId: string,
  options?: RequestInit,
): Promise<getJobApplicationResponse> => {
  return api<getJobApplicationResponse>(
    getGetJobApplicationUrl(applicationId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetJobApplicationQueryKey = (applicationId: string) => {
  return [`/applications/${applicationId}`] as const;
};

export const getGetJobApplicationQueryOptions = <
  TData = Awaited<ReturnType<typeof getJobApplication>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplication>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetJobApplicationQueryKey(applicationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getJobApplication>>
  > = ({ signal }) =>
    getJobApplication(applicationId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: applicationId !== null && applicationId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getJobApplication>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetJobApplicationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getJobApplication>>
>;
export type GetJobApplicationQueryError = ErrorType<unknown>;

export function useGetJobApplication<
  TData = Awaited<ReturnType<typeof getJobApplication>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplication>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobApplication>>,
          TError,
          Awaited<ReturnType<typeof getJobApplication>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetJobApplication<
  TData = Awaited<ReturnType<typeof getJobApplication>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplication>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobApplication>>,
          TError,
          Awaited<ReturnType<typeof getJobApplication>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetJobApplication<
  TData = Awaited<ReturnType<typeof getJobApplication>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplication>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Job Application
 */

export function useGetJobApplication<
  TData = Awaited<ReturnType<typeof getJobApplication>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplication>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetJobApplicationQueryOptions(applicationId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getJobApplicationFilesResponse200 = {
  data: GetJobApplicationFilesResponse;
  status: 200;
};

export type getJobApplicationFilesResponseSuccess =
  getJobApplicationFilesResponse200 & {
    headers: Headers;
  };
export type getJobApplicationFilesResponse =
  getJobApplicationFilesResponseSuccess;

export const getGetJobApplicationFilesUrl = (applicationId: string) => {
  return `/applications/${applicationId}/files`;
};

/**
 * Get all files for a job application
 * @summary Get Job Application Files
 */
export const getJobApplicationFiles = async (
  applicationId: string,
  options?: RequestInit,
): Promise<getJobApplicationFilesResponse> => {
  return api<getJobApplicationFilesResponse>(
    getGetJobApplicationFilesUrl(applicationId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetJobApplicationFilesQueryKey = (applicationId: string) => {
  return [`/applications/${applicationId}/files`] as const;
};

export const getGetJobApplicationFilesQueryOptions = <
  TData = Awaited<ReturnType<typeof getJobApplicationFiles>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplicationFiles>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetJobApplicationFilesQueryKey(applicationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getJobApplicationFiles>>
  > = ({ signal }) =>
    getJobApplicationFiles(applicationId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: applicationId !== null && applicationId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getJobApplicationFiles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetJobApplicationFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getJobApplicationFiles>>
>;
export type GetJobApplicationFilesQueryError = ErrorType<unknown>;

export function useGetJobApplicationFiles<
  TData = Awaited<ReturnType<typeof getJobApplicationFiles>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplicationFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobApplicationFiles>>,
          TError,
          Awaited<ReturnType<typeof getJobApplicationFiles>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetJobApplicationFiles<
  TData = Awaited<ReturnType<typeof getJobApplicationFiles>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplicationFiles>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobApplicationFiles>>,
          TError,
          Awaited<ReturnType<typeof getJobApplicationFiles>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetJobApplicationFiles<
  TData = Awaited<ReturnType<typeof getJobApplicationFiles>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplicationFiles>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Job Application Files
 */

export function useGetJobApplicationFiles<
  TData = Awaited<ReturnType<typeof getJobApplicationFiles>>,
  TError = ErrorType<unknown>,
>(
  applicationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getJobApplicationFiles>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetJobApplicationFilesQueryOptions(
    applicationId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type uploadJobApplicationFileResponse204 = {
  data: void;
  status: 204;
};

export type uploadJobApplicationFileResponseSuccess =
  uploadJobApplicationFileResponse204 & {
    headers: Headers;
  };
export type uploadJobApplicationFileResponse =
  uploadJobApplicationFileResponseSuccess;

export const getUploadJobApplicationFileUrl = (applicationId: string) => {
  return `/applications/${applicationId}/files`;
};

/**
 * Upload a file to a job application
 * @summary Upload Job Application File
 */
export const uploadJobApplicationFile = async (
  applicationId: string,
  uploadJobApplicationFileRequest?: UploadJobApplicationFileRequest,
  options?: RequestInit,
): Promise<uploadJobApplicationFileResponse> => {
  return api<uploadJobApplicationFileResponse>(
    getUploadJobApplicationFileUrl(applicationId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(uploadJobApplicationFileRequest),
    },
  );
};

export const getUploadJobApplicationFileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadJobApplicationFile>>,
    TError,
    { applicationId: string; data?: UploadJobApplicationFileRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadJobApplicationFile>>,
  TError,
  { applicationId: string; data?: UploadJobApplicationFileRequest },
  TContext
> => {
  const mutationKey = ['uploadJobApplicationFile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadJobApplicationFile>>,
    { applicationId: string; data?: UploadJobApplicationFileRequest }
  > = (props) => {
    const { applicationId, data } = props ?? {};

    return uploadJobApplicationFile(applicationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadJobApplicationFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadJobApplicationFile>>
>;
export type UploadJobApplicationFileMutationBody =
  | UploadJobApplicationFileRequest
  | undefined;
export type UploadJobApplicationFileMutationError = ErrorType<unknown>;

/**
 * @summary Upload Job Application File
 */
export const useUploadJobApplicationFile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadJobApplicationFile>>,
      TError,
      { applicationId: string; data?: UploadJobApplicationFileRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadJobApplicationFile>>,
  TError,
  { applicationId: string; data?: UploadJobApplicationFileRequest },
  TContext
> => {
  return useMutation(
    getUploadJobApplicationFileMutationOptions(options),
    queryClient,
  );
};
